spring:
  datasource:
    url: jdbc:postgresql://localhost:5400/postgres
    username: postgres
    password: example
    driver-class-name: org.postgresql.Driver
  jpa.generate-ddl: true
  jpa.database: postgresql
  jpa.database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  jpa:
    show-sql: false